/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package kft2;

import java.math.BigDecimal;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.text.NumberFormat;
import java.util.Locale;
import javax.swing.JOptionPane;
import javax.swing.text.AttributeSet;
import javax.swing.text.BadLocationException;
import javax.swing.text.PlainDocument;

/**
 *
 * @author Windows 7
 */
public class frmProduto extends javax.swing.JFrame {

    /**
     * Creates new form frmProduto
     */
    public frmProduto() {
        initComponents();
        setLocationRelativeTo( null );
        teclas();
    }
    
    Conexao bd = new Conexao();
    String sql;
    String pfc;
    boolean valido = false; 
    
             int onumero;
     public void dadospagina (int recebe){
         onumero = recebe;
         seila();
     }
     public void seila(){
                  sql = "select * from produto where ID =" + onumero ;
     
         try{
             
            ResultSet rs = bd.executarconsulta(sql);
            while(rs.next())
            {   
                txtcodigo.setText("" + rs.getInt("id"));
                txtdesc.setText(rs.getString("nome"));
                txtqtd.setText("" + rs.getInt("qtd"));
                double si = rs.getDouble("pr_und");
                NumberFormat formatomoeda = NumberFormat.getCurrencyInstance();

                txtvalorunit.setText("" + formatomoeda.format(si));
                
            }
        }
        catch (SQLException ex) {
            System.out.println("Problema na busca"); 
            }
     }     
     
    
    public void teclas (){
        txtcodigo.setDocument(new numeroproduto(10, "[^0-9]"));
        txtqtd.setDocument(new numeroproduto(5, "[^0-9]"));
        txtvalorunit.setDocument(new teclasmoedas());
        txtdesc.setDocument(new numeroproduto(10, "[^aA0-zZ9|]"));
    }
    
    
     class numeroproduto extends PlainDocument{
         int tam = 0;
         String regex = "";
         public numeroproduto (int a,String r){
             this.tam = a;
             this.regex = r;
         }
        @Override
        public void insertString(int offs, String str, AttributeSet a) throws BadLocationException {
            int tamanho = this.getLength() + str.length();
            if (tamanho <=tam){
            super.insertString(offs, str.replaceAll(regex,""), a); //To change body of generated methods, choose Tools | Templates.
            }
            else{              
            super.insertString(offs, str.replaceAll("[aA0-zZ9|^ |^!|^@|^#|^$|^%|^&|^*|^(|^)|^+|^_|^-|^;|^.|^,|^¨|^-|^~|^/|^´|^'|^^|^-|^}]", ""), a);
            }
            
            }
     }
         
         
    
    
    public void limpar()
    {
        txtcodigo.setText(null);
        txtdesc.setText(null);
        txtqtd.setText(null);
        txtvalorunit.setText(null);
    }
    public void verifica_cod(){
                 
     pfc = "select ID from produto where ID = " + txtcodigo.getText(); 
       
       try{
             
            ResultSet rs = bd.executarconsulta(pfc);
            while(rs.next())
            {   
            rs.getString("ID");
             valido = true;
            }
            
        }
        catch (SQLException ex) {
             valido = false;         
            } 
     }


    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        lblcodigo = new javax.swing.JLabel();
        lbldescricao = new javax.swing.JLabel();
        lblvalorUnit = new javax.swing.JLabel();
        lblqtd = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        txtcodigo = new javax.swing.JTextField();
        txtdesc = new javax.swing.JTextField();
        txtvalorunit = new javax.swing.JTextField();
        txtqtd = new javax.swing.JTextField();
        jPanel3 = new javax.swing.JPanel();
        btnnovo = new javax.swing.JButton();
        btnexcluir = new javax.swing.JButton();
        btnalterar = new javax.swing.JButton();
        btnbuscar = new javax.swing.JButton();
        btnvoltar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        lblcodigo.setText("Codigo:");

        lbldescricao.setText("Descrição:");

        lblvalorUnit.setText("Valor Unitario:");

        lblqtd.setText("Quantidade:");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblcodigo)
                    .addComponent(lblvalorUnit)
                    .addComponent(lbldescricao)
                    .addComponent(lblqtd))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblcodigo)
                .addGap(18, 18, 18)
                .addComponent(lbldescricao)
                .addGap(18, 18, 18)
                .addComponent(lblvalorUnit)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(lblqtd)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        txtvalorunit.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                txtvalorunitFocusLost(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txtvalorunit, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(txtcodigo, javax.swing.GroupLayout.DEFAULT_SIZE, 135, Short.MAX_VALUE)
                    .addComponent(txtdesc)
                    .addComponent(txtqtd))
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(txtcodigo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(txtdesc, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(txtvalorunit, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(txtqtd, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        btnnovo.setText("Novo");
        btnnovo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnnovoActionPerformed(evt);
            }
        });

        btnexcluir.setText("Excluir");
        btnexcluir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnexcluirActionPerformed(evt);
            }
        });

        btnalterar.setText("Atualizar");
        btnalterar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnalterarActionPerformed(evt);
            }
        });

        btnbuscar.setText("Buscar");
        btnbuscar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnbuscarActionPerformed(evt);
            }
        });

        btnvoltar.setText("Voltar");
        btnvoltar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnvoltarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnexcluir, javax.swing.GroupLayout.DEFAULT_SIZE, 71, Short.MAX_VALUE)
                    .addComponent(btnnovo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(btnbuscar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnalterar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnvoltar, javax.swing.GroupLayout.PREFERRED_SIZE, 69, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(26, 26, 26)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnnovo)
                    .addComponent(btnalterar)
                    .addComponent(btnvoltar))
                .addGap(33, 33, 33)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnexcluir)
                    .addComponent(btnbuscar))
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnvoltarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnvoltarActionPerformed
        // TODO add your handling code here:
        
        this.setVisible(false);
        new frmMenu().setVisible(true);
        
    }//GEN-LAST:event_btnvoltarActionPerformed

    private void btnnovoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnnovoActionPerformed
            // TODO add your handling code here:
        if (!txtcodigo.getText().equals("") && !txtdesc.getText().equals("") && !txtqtd.getText().equals("") && !txtvalorunit.getText().equals("")){
        verifica_cod();
         if(valido==false){
             NumberFormat formatomoeda = NumberFormat.getCurrencyInstance();
             String s0 = txtvalorunit.getText();
             String vsf = s0.replace("R$", "").replace(" ", "").replace(".", "").replace(",", ".");
             System.out.println(vsf);
             double si =  Double.parseDouble(vsf);

             formatomoeda.format(si);
             
        sql = "insert into produto values(" + 
                txtcodigo.getText() + ",'" +
                txtdesc.getText() + "'," +
                Integer.parseInt(txtqtd.getText())
                + "," + si + ")";
        if(bd.executarcomandos(sql) > 0)
        {
            JOptionPane.showMessageDialog(null, "Cadastro efetuado com sucesso");        
            limpar();
        }
         }
         
   else {
       JOptionPane.showMessageDialog(null,"ID ja Cadastrado"); 
       valido=false;
               
   }
        }
        else{
            JOptionPane.showMessageDialog(null,"Todos os campos são obrigadorio");
        }
    }//GEN-LAST:event_btnnovoActionPerformed

    private void btnalterarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnalterarActionPerformed
        // TODO add your handling code here:
        if (!txtcodigo.getText().equals("") && !txtdesc.getText().equals("") && !txtqtd.getText().equals("") && !txtvalorunit.getText().equals("")){
            NumberFormat formatomoeda = NumberFormat.getCurrencyInstance();
             String s0 = txtvalorunit.getText();
             String vsf = s0.replace("R$", "").replace(" ", "").replace(".", "").replace(",", ".");
             
            sql = "update produto set nome = '" + txtdesc.getText() 
                + "', qtd = " + Integer.parseInt(txtqtd.getText())
                + ", pr_und = " + Double.parseDouble(vsf)
                + " where id = " + txtcodigo.getText();                  
        if(bd.executarcomandos(sql) > 0)
        {
            JOptionPane.showMessageDialog(null, "Atualização efetuada com sucesso");        
            limpar();
        }
        }
        else{
    
            JOptionPane.showMessageDialog(null,"Todos os campos são obrigadorio");
        }
        
    }//GEN-LAST:event_btnalterarActionPerformed

    private void btnexcluirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnexcluirActionPerformed
        // TODO add your handling code here:
        if (!txtcodigo.getText().equals("")){
            sql = "delete from produto where ID = " + txtcodigo.getText();  
         if(bd.executarcomandos(sql) > 0)
        {
            JOptionPane.showMessageDialog(null, "Exclusão efetuada com sucesso");        
            limpar();
        }
         else{
             JOptionPane.showMessageDialog(null,"ID não cadastrado");
        }
         }
        
        else {
            JOptionPane.showMessageDialog(null,"Campo ID obrigadorio");
        }
    }//GEN-LAST:event_btnexcluirActionPerformed

    private void btnbuscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnbuscarActionPerformed
        // TODO add your handling code here:
        boolean s3 = false;
     if(!txtcodigo.getText().equals("") || !txtdesc.getText().equals("")){   
         if (!txtcodigo.getText().equals("")){
         sql = "select * from produto where ID = " + txtcodigo.getText();
         }
         else{
         sql = "select * from produto where nome = '" + txtdesc.getText() + "'";
         }
         try{
             
            ResultSet rs = bd.executarconsulta(sql);
            while(rs.next())
            {   
                txtcodigo.setText("" + rs.getInt("id"));
                txtdesc.setText(rs.getString("nome"));
                txtqtd.setText("" + rs.getInt("qtd"));
                double si = rs.getDouble("pr_und");
                NumberFormat formatomoeda = NumberFormat.getCurrencyInstance();

                txtvalorunit.setText("" + formatomoeda.format(si));
                s3 = true;
                
            }
        }
        catch (SQLException ex) {
            System.out.println("Problema na busca"); 
            s3 = false;
            }
     }     
     else{
         JOptionPane.showMessageDialog(null, "Campo Codigo ou Descrição obrigadorio"); 
          s3 = true;
     }
     
     if(s3==false){
         JOptionPane.showMessageDialog(null, "Produto não cadastrado"); 
         s3 = true;
         limpar();
     }
    }//GEN-LAST:event_btnbuscarActionPerformed

    private void txtvalorunitFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtvalorunitFocusLost
         String valortotal = txtvalorunit.getText().replace("R$", "").replace(" ", "").replace(".", "").replace(",", ".");

        double sj = Double.parseDouble(valortotal);
        NumberFormat formatomoeda = NumberFormat.getCurrencyInstance();
          txtvalorunit.setText(""+formatomoeda.format(sj));
       
        
    }//GEN-LAST:event_txtvalorunitFocusLost

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(frmProduto.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(frmProduto.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(frmProduto.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(frmProduto.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new frmProduto().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnalterar;
    private javax.swing.JButton btnbuscar;
    private javax.swing.JButton btnexcluir;
    private javax.swing.JButton btnnovo;
    private javax.swing.JButton btnvoltar;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JLabel lblcodigo;
    private javax.swing.JLabel lbldescricao;
    private javax.swing.JLabel lblqtd;
    private javax.swing.JLabel lblvalorUnit;
    private javax.swing.JTextField txtcodigo;
    private javax.swing.JTextField txtdesc;
    private javax.swing.JTextField txtqtd;
    private javax.swing.JTextField txtvalorunit;
    // End of variables declaration//GEN-END:variables
}
